#[[
   Copyright 2026, Float314 and contributors.

   Licensed under the Berkeley Software Distribution License, BSD 4-Clause
    License (the "License"); you may not use this file except in compliance with
    the License. You may obtain a copy of the License at

    https://choosealicense.com/licenses/bsd-4-clause/

    THIS SOFTWARE IS PROVIDED BY COPYRIGHT HOLDER "AS IS" AND ANY EXPRESS OR
    IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
    MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
    EVENT SHALL COPYRIGHT HOLDER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
    SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
    PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
    OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
    WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
    OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
function(execbrand_embedrc target json) 
    set(json_path "${CMAKE_CURRENT_SOURCE_DIR}/${json}")
    if(NOT EXISTS "${json_path}")
        message(FATAL_ERROR "[EXECBRANDER] JSON file not found: ${json_path}. Skipping metadata.rc generation.")
    elseif(EXISTS "${json_path}")
        file(READ "${json_path}" json_content)

        # Assign JSON Content into indiv variables, cause what the fuck happened to classes? 
        string(JSON ProjName GET "${json_content}" "name")
        string(JSON description GET "${json_content}" "description")
        string(JSON company GET "${json_content}" "company")
        string(JSON ProjVersion GET "${json_content}" "version")
        string(JSON copyright GET "${json_content}" "copyright")
        string(JSON icon GET "${json_content}" "icon")

        # Give message of the Found data
        message("Found Metadata resource! Details: ")
        message("Name: ${ProjName}")
        message("Description: ${description}")
        message("Company: ${company}")
        message("Version: ${ProjVersion}")
        message("Copyright: ${copyright}")
        message("Icon: ${icon}")

        # Generate RC File 
        file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/metadata.rc" "
/*
    This file was generated by execbrander CMake Module. 
    DO NOT EDIT THIS FILE DIRECTLY. Instead, edit the JSON file and re-run CMake to regenerate this file.

    That was a warning, not an insult. Just edit the file if you know what you're doing, and if you don't,
    then don't edit it at all. You're better off understanding JSON than RC files, trust me.

    Also one important thing, Github of this project (execbrander) - 
        <https://github.com/Float314/execbrander> - is the place to report issues, ask for help, or contribute.
*/

#include <winrc.h>
#include <windows.h> 

1 VERSIONINFO
FILEVERSION 1,0,0,0
PRODUCTVERSION 1,0,0,0
FILEOS 0x40004
FILETYPE 0x1
{
BLOCK \"StringFileInfo\"
{
	BLOCK \"040904B0\"
	{
		VALUE \"FileDescription\", \"${description}\"
		VALUE \"InternalName\", \"${ProjName}\"
		VALUE \"OriginalFilename\", \"${ProjName}\"
		VALUE \"CompanyName\", \"${company}\"
		VALUE \"LegalCopyright\", \"${copyright}\"
		VALUE \"ProductName\", \"${ProjName}\"
		VALUE \"FileVersion\", \"${ProjVersion}\"
		VALUE \"ProductVersion\", \"${ProjVersion}\"
	}
}

BLOCK \"VarFileInfo\"
{
	VALUE \"Translation\", 0x0409 0x04B0
}
}

")

        # Link RC File to Executable
        target_sources(${target} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/metadata.rc")
        message("[EXECBRANDER] metadata.rc generated and linked to target '${target}'.")

        # Copy Icon to Binary Directory if it exists
        if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${icon}")
            file(COPY "${CMAKE_CURRENT_SOURCE_DIR}/${icon}" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}")
            message("[EXECBRANDER] Icon file '${icon}' copied to binary directory.")
        else()
            message(WARNING "[EXECBRANDER] Icon file '${icon}' not found. Skipping icon embedding.")
        endif()

    endif() # EXISTS {$json_path}

endfunction()